org:
service: hotel-booking-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  SeedRooms:
    handler: functions/SeedRooms/index.handler
    events:
      - httpApi:
          path: /seed/rooms
          method: post
  GetAllBooking:
    handler: functions/GetAllBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get
  CreateBooking:
    handler: functions/CreateBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post
  UpdateBooking:
    handler: functions/UpdateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: put
  CancelBooking:
    handler: functions/CancelBooking/index.handler
    events:
      - httpApi:
          path: /bookings/cancel
          method: delete

resources:
  Resources:
    HotelBookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hotel-bookings
        AttributeDefinitions:
          - AttributeName: "bookingId"
            AttributeType: "S"
          - AttributeName: "checkInDate"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "bookingId"
            KeyType: HASH
          - AttributeName: "checkInDate"
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: CheckInDateIndex
            KeySchema:
              - AttributeName: "checkInDate"
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"

    HotelRoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hotel-rooms
        AttributeDefinitions:
          - AttributeName: "roomId"
            AttributeType: "S"
          - AttributeName: "roomType"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "roomId"
            KeyType: HASH
          - AttributeName: "roomType"
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
