org: emanuelejs23
service: hotel-booking-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::575108945643:role/serverless

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  SeedRooms:
    handler: functions/SeedRooms/index.handler
    events:
      - httpApi:
          path: /seed/rooms
          method: post
  GetBooking:
    handler: functions/GetBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: get
  GetAllBooking:
    handler: functions/GetAllBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get
  CreateBooking:
    handler: functions/CreateBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post
  UpdateBooking:
    handler: functions/UpdateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: put
  GetAvailableRooms:
    handler: functions/GetAvailableRooms/index.handler
    events:
      - httpApi:
          path: /rooms/available
          method: get

resources:
  Resources:
    HotelBookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hotel-bookings
        AttributeDefinitions:
          - AttributeName: "bookingId"
            AttributeType: "S"
          - AttributeName: "checkInDate"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "bookingId"
            KeyType: HASH
          - AttributeName: "checkInDate"
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: CheckInDateIndex
            KeySchema:
              - AttributeName: "checkInDate"
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
